doctrine:
    dbal:
        url: 'mysql://%env(resolve:HOT_STORAGE_USER)%:%env(urlencode:HOT_STORAGE_PASSWORD)%@%env(resolve:HOT_STORAGE_HOST)%:%env(resolve:HOT_STORAGE_PORT)%/%env(resolve:HOT_STORAGE_DB_NAME)%?serverVersion=%env(resolve:HOT_STORAGE_MYSQL_VERSION)%&charset=UTF8'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

