parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    HouseHunter\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    Fraud\Application\Bootstrap\EscapingMysqlPasswordEnvVar: ~

    HouseHunter\CLI\Scrapper:
        arguments:
            $destinationUrl: '%env(resolve:SEARCHES)%'
            $telegramChatId: '%env(resolve:TELEGRAM_CHAT_ID)%'
            $telegramToken: '%env(resolve:TELEGRAM_TOKEN)%'
            $sleepTimeInMinutes: '%env(resolve:SCRAP_EVERY_MINUTES)%'
            $isFakeRequest: '%env(resolve:FAKE_CALL)%'